@startuml restaurante
left to right direction
actor Cliente as c
package Profissional {
  actor "Supervisor de Alimentos" as sa
  actor Chefe as ch
  actor cozinheira as co 
  actor barman as ba 
  actor coqueteleiro as coq

}
package Restaurante {
  usecase "Comer alimento" as UC1
  usecase "Pagar" as UC2
  usecase "Beber" as UC3
  usecase "Analisar alimento" as UC4
  (UC1) .> (UC2) : include
  (UC3) .> (UC2) : <<extends>>
}
sa -- UC4
c -- UC1
c -- UC2
c -- UC3
sa <|-- ch
@enduml